name: Enable user management1

on: [push]
# on: 
#   workflow_dispatch:
jobs:
  deploy:
    name: enable user management 1
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      
    - name: enable um
      run: |
        # Find the dir
        directory_id=$(aws ds describe-directories --query "DirectoryDescriptions[?Name=='corp.example.com'].DirectoryId" --output text)
        echo "dir: $directory_id"

        # Checking if Data Access is enabled
        status=$(aws ds describe-directories --directory-ids $directory_id --query "DirectoryDescriptions[0].DataAccessState" --output text)
        echo $status

        # temporarily disable the script's default behavior of exiting on errors 
        set +e
        # Enabling directory Data Access
        aws ds enable-directory-data-access --directory-id $directory_id
        set -e
        

        # create user
        echo "creating user"
        aws ds-data create-user --directory-id $directory_id --sam-account-name "paddingdon.brown" --other-attributes '{ "DisplayName": { "S": "paddington.brown"} }'